from django.conf.urls import patterns, include, url
from ManagementTool.views import *
#from ManagementTool.views import default,login,ip_san,index,administrator,resources,monitor,auditors,logout_user,detailed,onlineloder,delete,deletenode,changenode,addauditor,alarmsetting,enableuser,deleteuser,addnode,change_passwd
#from ManagementTool.views import delete_black,addlu,addnode_real,adduser_real,addlun,delete_lun,addlu_lun,add_black,set_ipfilter,monitor_info_node,monitor_info_cluster,saveemail,testemail,export,addlu_real,get_user_type,alarm_msg
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
#import django_cron
#django_cron.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ManagementTool.views.home', name='home'),
    # url(r'^ManagementTool/', include('ManagementTool.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	(r'^$',default),
	(r'^index/$',index),
	(r'^login/$',login),
	(r'^logout_user/$',logout_user),
	#(r'^alarm_msg/$',alarm_msg),
	(r'^fc_san/$',fc_san),
	#(r'^ip_san/$',ip_san),
	(r'^export/$',export),
	(r'^reset_login/$',reset_login),

	url(r'^resources_monitor/$',resources_monitor,name='resources_monitor'),
	url(r'^rm_cluster/$',rm_cluster,name='rm_cluster'),
	url(r'^rm_nodes/$',rm_nodes,name='rm_nodes'),
	url(r'^sm_ip_san/$',sm_ip_san,name='sm_ip_san'),
	url(r'^sm_onlineloader/$',sm_onlineloader,name='sm_onlineloader'),
	url(r'^sm_change_target/$',sm_change_target,name='sm_change_target'),
	url(r'^sm_delete_target/$',sm_delete_target,name='sm_delete_target'),
	url(r'^sm_modify_ip_chap/$',sm_modify_ip_chap,name='sm_modify_ip_chap'),
	url(r'^sm_addlun/$',sm_addlun,name='sm_addlun'),
	url(r'^sm_dellun/$',sm_dellun,name='sm_dellun'),
	url(r'^sm_addblack/$',sm_addblack,name='sm_addblack'),
	url(r'^sm_delblack/$',sm_delblack,name='sm_delblack'),
	url(r'^sm_add_target/$',sm_add_target,name='sm_add_target'),
	url(r'^sm_add_target_action/$',sm_add_target_action,name='sm_add_target_action'),
	url(r'^sm_recover_target/$',sm_recover_target,name='sm_recover_target'),
	url(r'^sm_fc_san/$',sm_fc_san,name='sm_fc_san'),
	url(r'^sm_lun_assign/$',sm_lun_assign,name='sm_lun_assign'),
	url(r'^sm_service_conf/$',sm_service_conf,name='sm_service_conf'),
	url(r'^sm_service_conf_action/$',sm_service_conf_action,name='sm_service_conf_action'),
	url(r'^sm_fc_service/$',sm_fc_service,name='sm_fc_service'),
	url(r'^em_nodes/$',em_nodes,name='em_nodes'),
	url(r'^em_change_node/$',em_change_node,name='em_change_node'),
	url(r'^em_del_node/$',em_del_node,name='em_del_node'),
	url(r'^em_add_node/$',em_add_node,name='em_add_node'),
	url(r'^em_add_node_action/$',em_add_node_action,name='em_add_node_action'),
	url(r'^em_zone/$',em_zone,name='em_zone'),
	url(r'^em_zone_action/$',em_zone_action,name='em_zone_action'),
	url(r'^em_cluster/$',em_cluster,name='em_cluster'),
	url(r'^em_change_cache/$',em_change_cache,name='em_change_cache'),
	url(r'^em_change_cache_action/$',em_change_cache_action,name='em_change_cache_action'),
	url(r'^em_shutdown/$',em_shutdown,name='em_shutdown'),
	url(r'^em_shutdown_action/$',em_shutdown_action,name='em_shutdown_action'),
	url(r'^alarm_management/$',alarm_management,name='alarm_management'),
	url(r'^am_manage/$',am_manage,name='am_manage'),
	url(r'^am_search/$',am_search,name='am_search'),
	url(r'^am_handle/$',am_handle,name='am_handle'),
	url(r'^am_setting/$',am_setting,name='am_setting'),
	url(r'^am_setting_save/$',am_setting_save,name='am_setting_save'),
	url(r'^am_email/$',am_email,name='am_email'),
	url(r'^am_email_save/$',am_email_save,name='am_email_save'),
	url(r'^am_email_test/$',am_email_test,name='am_email_test'),
	url(r'^uesr_management/$',uesr_management,name='uesr_management'),
	url(r'^um_setting/$',um_setting,name='um_setting'),
	url(r'^um_add_user/$',um_add_user,name='um_add_user'),
	url(r'^um_add_user_action/$',um_add_user_action,name='um_add_user_action'),
	url(r'^um_enable_user/$',um_enable_user,name='um_enable_user'),
	url(r'^um_delete_user/$',um_delete_user,name='um_delete_user'),
	url(r'^help_management/$',help_management,name='help_management'),
	url(r'^hm_introductions/$',hm_introductions,name='hm_introductions'),
	url(r'^hm_about/$',hm_about,name='hm_about'),

	url(r'^au_search/$',au_search,name='au_search'),

	url(r'^addlu_real/$',addlu_real,name='addlu_real'),
	url(r'^sm_recover_target/$',sm_recover_target,name='sm_recover_target'),
	url(r'^sm_recover_target_action/$',sm_recover_target_action,name='sm_recover_target_action'),
	url(r'^change_passwd/$',change_passwd,name='change_passwd'),
	#(r'^online_loader/$',online_loader),
	#(r'^administrator/$',administrator),
	#url(r'^adduser_real/$',adduser_real,name='adduser_real'),
	#(r'^messadd_user/$',messadd_user),
	#(r'^resources/$',resources),
	#url(r'^saveemail/$',saveemail,name='saveemail'),
	#url(r'^testemail/$',testemail,name='testemail'),
	#url(r'^deleteuser/$',deleteuser,name='deleteuser'),
	#url(r'^addnode_real/$',addnode_real,name='addnode_real'),
	url(r'^add_black/$',add_black,name='add_black'),
	url(r'^addlu_lun/$',addlu_lun,name='addlu_lun'),
	url(r'^del_lun_web/$',del_lun_web,name='del_lun_web'),
	url(r'^del_black_web/$',del_black_web,name='del_black_web'),
	#(r'^delete/$',delete),
	#(r'^monitor_info_node/$',monitor_info_node),
	(r'^get_user_type/$',get_user_type),
	#(r'^monitor_info_cluster/$',monitor_info_cluster),
	#(r'^detailed/(?P<lu_name>\w+)/(?P<lu_ip>\w+)/$',detailed),
	#url(r'^detailed/$',detailed,name='detailed'),
	#url(r'^onlineloder/$',onlineloder,name='onlineloder'),
	#url(r'^alarmsetting/$',alarmsetting,name='alarmsetting'),
	#url(r'^delete/$',delete,name='delete'),
	url(r'^set_ipfilter/$',set_ipfilter,name='set_ipfilter'),
	(r'^monitor/$',monitor),
	(r'^auditors/$',auditors),
	url(r'^addlu/$',addlu,name='addlu'),
	#url(r'^addnode/$',addnode,name='addnode'),
	(r'^addauditor/$',addauditor),
#	(r'^auditors/$',auditors),
	(r'^accounts/login/$','django.contrib.auth.views.login',{'template_name':'/opt/ybs/ybsmt/YBS/templates/login.html'}),

)
